name: Local Test Workflow

on:
  workflow_dispatch:

jobs:
  test-workflow:
    name: Test Performance Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
          
      - name: Start application service
        run: |
          # Start the application in background
          python src/app.py &
          echo $! > app.pid
          sleep 5 # Give time for the app to start
          
      - name: Run performance tests
        run: |
          # Run performance tests locally
          python -m pytest src/performance_tests.py -v --html=reports/performance_report.html
          
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-reports
          path: reports/
          
      - name: Generate summary report
        run: |
          echo "## Performance Test Results" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "reports/performance_report.html" ]; then
            echo "Performance report generated successfully." >> $GITHUB_STEP_SUMMARY
          fi